spring:
  application:
    name: springboot-init
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 7529
  servlet:
    context-path: /api

gear:
  wenxin:
    access-token:
