spring:
  application:
    name: springboot-init
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 7529
  servlet:
    context-path: /api

gear:
  wenxin:
#    api-key: Yo1qSiTCYsdjkfhkpQbpfsdfWwPei
#    secret-key: tYsdfM2aGsdfsdfFQGzGkdwBhjkhnjN6
    chat-glm2-6b-url: http://asdhkjashdkjas
    star-coder-url: http://asdhkjashdkjas
    access-token: 2sdf313.asdfsd21.232dfgher3231231.23resdfgd
